# Generated by Django 5.2.12 on 2026-03-28 05:36

import apps.placements.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "contractor_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "approval_flow",
                    models.CharField(
                        choices=[
                            ("BROKER_ONLY", "Broker Only"),
                            ("CLIENT_THEN_BROKER", "Client Then Broker"),
                        ],
                        default="BROKER_ONLY",
                        max_length=20,
                    ),
                ),
                ("require_timesheet_attachment", models.BooleanField(default=False)),
                ("client_can_view_invoices", models.BooleanField(default=False)),
                ("client_can_view_documents", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="clients.client",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "placements",
            },
        ),
        migrations.CreateModel(
            name="PlacementDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.placements.models.placement_document_path
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.IntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="placements.placement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "placement_documents",
            },
        ),
    ]
