# Generated by Django 5.2.12 on 2026-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
