# Generated by Django 5.2.12 on 2026-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0002_placement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="payment_terms_client_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placement",
            name="payment_terms_contractor_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
