# Generated by Django 5.2.12 on 2026-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0003_placement_payment_terms_client_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementdocument",
            name="visible_to_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="placementdocument",
            name="visible_to_contractor",
            field=models.BooleanField(default=False),
        ),
    ]
