# Generated by Django 5.2.12 on 2026-03-31 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_rename_name_invoicetemplate_title_and_more"),
        ("placements", "0004_placementdocument_visible_to_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="client_invoice_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="placements_as_client_template",
                to="invoices.invoicetemplate",
            ),
        ),
    ]
