# Generated by Django 5.2.13 on 2026-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_add_client_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
