# Generated by Django 5.2.12 on 2026-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
