# Generated by Django 5.2.12 on 2026-03-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgencySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_payment_terms_client_days", models.IntegerField(default=30)),
                (
                    "default_payment_terms_contractor_days",
                    models.IntegerField(default=35),
                ),
            ],
            options={
                "db_table": "agency_settings",
            },
        ),
    ]
