# Generated by Django 5.2.12 on 2026-03-31 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0001_agency_settings"),
        ("invoices", "0004_rename_name_invoicetemplate_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencysettings",
            name="default_client_invoice_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="invoices.invoicetemplate",
            ),
        ),
    ]
