# Generated by Django 5.2.12 on 2026-03-28 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("vat_registered", models.BooleanField(default=False)),
                (
                    "vat_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vat_rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "invoice_series_prefix",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("next_invoice_number", models.IntegerField(default=1)),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bank_account_iban",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "bank_swift_bic",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("payment_terms_days", models.IntegerField(blank=True, null=True)),
                ("billing_address", models.TextField(blank=True, default="")),
                ("country", models.CharField(default="", max_length=100)),
                ("default_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contractor_profiles",
            },
        ),
    ]
