# Generated by Django 5.2.12 on 2026-04-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorprofile",
            name="code",
            field=models.CharField(blank=True, default="", max_length=4, unique=True),
        ),
    ]
