# Generated by Django 5.2.13 on 2026-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_add_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='candidate_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
