# Generated by Django 5.2.13 on 2026-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_add_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
