# Generated by Django 5.2.12 on 2026-03-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="billing_address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
