# Generated by Django 5.2.12 on 2026-04-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_billing_address_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="code",
            field=models.CharField(blank=True, default="", max_length=4, unique=True),
        ),
    ]
