# Generated by Django 5.2.13 on 2026-04-11 06:35

import apps.clients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('MEETING', 'Meeting'), ('CALL', 'Call'), ('PROPOSAL_SENT', 'Proposal Sent'), ('CONTRACT_SIGNED', 'Contract Signed'), ('STATUS_CHANGE', 'Status Change'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_REMOVED', 'File Removed')], max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('old_value', models.CharField(blank=True, default='', max_length=50)),
                ('new_value', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.clients.models.client_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('PROPOSAL', 'Proposal'), ('NDA', 'Nda'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='clients.clientactivity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
