# Generated by Django 5.2.12 on 2026-03-28 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("placements", "0001_initial"),
        ("timesheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("CLIENT_INVOICE", "Client Invoice"),
                            ("CONTRACTOR_INVOICE", "Contractor Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vat_rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("VOIDED", "Voided"),
                            ("CORRECTED", "Corrected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("billing_snapshot", models.JSONField(default=dict)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="placements.placement",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="timesheets.timesheet",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceCorrectionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrective_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrects",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "original_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_link",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_correction_links",
            },
        ),
    ]
