# Generated by Django 5.2.12 on 2026-03-30 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("invoices", "0002_invoicenotification"),
        ("placements", "0002_placement_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("CONTRACTOR", "Contractor"),
                            ("CLIENT", "Client"),
                            ("AGENCY", "Agency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("billing_address", models.TextField(blank=True, default="")),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "default_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("vat_registered", models.BooleanField(null=True)),
                (
                    "vat_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vat_rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bank_account_iban",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "bank_swift_bic",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "invoice_series_prefix",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("next_invoice_number", models.IntegerField(blank=True, null=True)),
                ("payment_terms_days", models.IntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_templates",
                        to="clients.client",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="invoices.invoicetemplate",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_templates",
                        to="placements.placement",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_templates",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True), ("status", "ACTIVE")),
                        fields=("contractor", "template_type"),
                        name="unique_default_active_per_contractor_type",
                    )
                ],
            },
        ),
    ]
