# Generated by Django 5.2.12 on 2026-03-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoicetemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoicetemplate",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="invoicetemplate",
            name="code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
