# Generated by Django 5.2.12 on 2026-04-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_rename_name_invoicetemplate_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
