# Generated by Django 5.2.12 on 2026-04-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_add_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="counters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="invoice_series_prefix",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
