# Generated by Django 5.2.13 on 2026-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_add_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
